# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил:
- Боровягин Данил Андреевич
- ПИЭ-21-2

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1

### Наверняка вы думаете, что декораторы - это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто "возьмёт их из этого декоратора"). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи.
P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.

```python
from functools import *


@lru_cache(None)
def fib(n):
    if n <= 1:
        return n
    else:
        return fib(n - 1) + fib(n - 2)


print(fib(100))


def fib1(n):
    if n <= 1:
        return n
    else:
        return fib1(n - 1) + fib1(n - 2)


print(fib1(100))


```


### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/lab_10/1.jpg)

## Выводы

На примере двух данных скриптов мы видим что про помощи декоротора программа моментально выдаёт огромное значение, но если вдруг мы решим найти это же значение без использования декоратора, то время выполнения составит по меньшей меребе более 3 минут, столько я ожидал но результат так и не был выдан. Ещё я заметил странность в написаном вами коде, а именной у вас конструкция с `elif` хотя можно просто устоновить знак <= и смысл будет тотже но код станет чуть компактней.`@lru_cache(None)` данный декоратор отвечает за кеширование результатов вызова функции, а указание `None` указывает на не ограниченное кеширование.

## Лабораторная работа №2

### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

```python
def check(func):
    def out(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 100:
            age = "недопустимы вовраст "
        func(name, age)

    return out


@check
def person(name, age):
    print(f"имя: {name} возраст: {age}")


person('Владимир', 38)
person("Александр", -5)
person('Петр', 138, 15, 48, 2)
```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/lab_10/2.jpg)

## Вывод

В данном коде мы видим наглядно как можно создать декоратор, как я понял преимущество декорота ещё в том что в него можно обернуть другую функцию без изменения её кода и без необходимости вызывать функцию которая была преоброзована в декоратор.

## Лабораторная работа №3

### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string.
Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

```python
def check(func):
    def out(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 100:
            age = "недопустимы вовраст "
        func(name, age)

    return out


def data(*args):
    try:
        for i in range(len(*args)):
            try:
                res = (args[0][i] * 15) // 10
                print(res)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print("вся информация обработана")


@check
def person(name, age):
    print(f"имя: {name} возраст: {age}")


person('Владимир', 38)
person("Александр", -5)
person('Петр', 138, 15, 48, 2)

data([1, 15, "hell", 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])

```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/lab_10/3.jpg)

## Вывод

В данном коде мы видимо как можно создать исключение при помощи конструкции `try, except, finally` в нашем случае сначала мы узнаём длинну списка в цикле `for` затем поочериди каждую переменную проганяем через подсчёт. вслучае ошибки мы ссылаемся на ошибку и выводим её на экран при помощи ` Exception `


## Лабораторная работа №4

### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться "Успешная регистрация"

```python
class Negativ(Exception):
    pass


def check(name):
    if len(name) > 10:
        raise Negativ("длинна более 10 символов")
    else:
        print("успешная регестрация")


name_one = "вольгортонирын"
check(name_one)

```
### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/lab_10/4.jpg)
 
## Выводы

В данном примере кода мы видим как можно создавать собственные исключения. `raise` как я понял нужен для перехвата то есть если длинна имени больше 10 выводи ошибку длинна более 10 символов

## Лабораторная работа №5

### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: init () (вызывается при создании класса декоратора в программе) и call () (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class check:
    def __init__(self, func):
        print("> класс check метод __init__ успешный запуск")
        self.func = func

    def __call__(self):
        print("> проверка перед запуском", self.func.__name__)
        self.func()
        print("> Проверка безопасного подключения")


@check
def site():
    print("сайт работает")


print(">> сайт запущен")
site()
print(">> сайт выключен")

```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/lab_10/5.jpg)

## Выводы

На примере данного кода мы видим каким оброзом ещё можно использовать декаратор, а именно мы образаемся к функции `site` но перед ней декоратор то вся сразу переходит в наш класс где сначала выводится надпись проверка перед запуском, затем выполняется наша функция, а именно выводит надпись сайт работает, далее продолжается наш декоратор, а именно проверка безопасного выключения. На это мработа декоратора законче и выводится последнее собщение сайт выключен.

## Самостоятельная работа №1

### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
Подсказка: необходимо использовать модуль time
Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы.
Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды.

```python
import time


def time1(func):
    def wra():
        start_time = time.time()
        result = func()
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"\nВремя выполнения функции {func.__name__}: {execution_time} секунд")
        return result
    return wra


@time1
def fib():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')


fib()

```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/1.jpg)

## Вывод

В данном коде мы высчитваем время выполнения програмы очень простым способом, программа запоминает когда код начал выполнение(время начала) и когда закончил выпонение(время конца) затем просто отнимает конец от начала и получаем затраченное время на выполнение кода. так же я понял что декоратором может быть функция и потом можно будет применять эту функцию на разные части кода при этом не обращаясь к ней через код, а прост оприменив декоратор, это сильно сокращает код и упращает его понимание.

## Самостоятельная работа №2

###  Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение ("бросить исключение") и вывести в консоль "файл пустой", а если он не пустой, то вывести информацию из файла.

```python
try:
    with open("3.txt", "r") as f:
        content = f.read()
        if content:
            print("содержимое файла: ")
            print(content)
        else:
            raise Exception("файл пустой ")
except Exception as ex:
    print(ex)

```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/2.1.jpg)

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/2.2.jpg)

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/2.3.jpg)

## Вывод

В данном коде мы самостоятельно попробывали применить кострукцию `try, except` проверка на наличие информации происходит при помощи цикла `if`. Вообще данная конструкция может быть черезвычайна полезна в крупных проектах. 

## Самостоятельная работа №3

### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка "Неподходящий тип данных. Ожидалось число.". Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
try:
    user = input("Введите число для сложения: ")


    def sumi(user1):
        res = int(user1) + 2
        return res


    result = sumi(user)
    print(result)
except ValueError:
    print("Не подходящий тип данных. Ожидалось число")

```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/3.1.jpg)

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/3.2.jpg)

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/3.3.jpg)

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/3.4.jpg)

## Листинг

Запрашивает у пользователя ввод числа для сложения с помощью функции `input`.
Определяет функцию `sumi`, которая принимает один аргумент `user1`. Внутри функции выполняется сложение преобразованного в целое число `user1` и числа 2.
Вызывает функцию `sumi` с введенным пользователем числом user и сохраняет результат сложения в переменной `result`.
Выводит результат сложения на экран с помощью функции `print`.
Если возникает исключение `ValueError` (например, если пользователь ввел нечисловое значение), перехватывает исключение и выводит сообщение "Не подходящий тип данных. Ожидалось число" с помощью функции `print`.

## Самостоятельная работа №4

### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
def area_decorator(func):
    def wrapper(*args, **kwargs):  # функция принимает любое количество аргументов
        print("Вычисление площади начато...")  # выводим надпись
        result = func(*args, **kwargs)  # вызов оригинальной функции
        print("Вычисление площади завершено.")  # выводим надпись
        return result  # возвращаем значение
    return wrapper  # возвращаем значение


@area_decorator
def rectangle_area(length, width):  # функция для рассчёта площади
    return length * width  # формула для подсчёта


@area_decorator
def circle_area(radius):  # функция для рассчёта площади
    return 3.14 * radius**2  # формула для подсчёта


def main():  # для выбора действия и ввода даных пользователем
    print("Выберите фигуру:")  # выводим надпись
    print("1. Прямоугольник")  # выводим надпись
    print("2. Круг")  # выводим надпись
    choice = input("Введите номер фигуры (1-2): ")  # выводим надпись

    if choice == "1":
        length = float(input("Введите длину прямоугольника: "))  # ввод данных
        width = float(input("Введите ширину прямоугольника: "))  # ввод данных
        area = rectangle_area(length, width)  # передаём данные в функцию
        print("Площадь прямоугольника:", area)  # выводим надпись с площадью

    elif choice == "2":
        radius = float(input("Введите радиус круга: "))  # ввод данных
        area = circle_area(radius)  # передаём данные в функцию
        print("Площадь круга:", area)  # выводим надпись с площадью

    else:
        print("Неверный выбор.")  # выводим надпись


main()  # вызываем функцию

```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/4.1.jpg)

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/4.2.jpg)

## Самостоятельная работа №5

### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.с

```python
class CustomException(Exception):  # класс наследующий от класса Exception
    pass  # пустой блок


def process_data(data):
    if data == "error":
        raise CustomException("Произошла ошибка обработки данных")  # Возбуждаем пользовательское исключение CustomException с сообщением об ошибке
    else:
        print("Данные успешно обработаны:", data)  # Выводим сообщение об успешной обработке данных


input_data = input("Введите данные: ")  # Запрашиваем у пользователя ввод данных
process_data(input_data)  # Вызываем функцию для обработки данных


num = int(input("Введите число: "))  # Запрашиваем у пользователя ввод числа и преобразуем его в целое число
if num < 0:
    raise CustomException("Число должно быть положительным")  # пользовательское исключение, если число с минусом
else:
    print("Число введено корректно:", num)  # Выводим сообщение о корректном вводе числа

```

### Результат.

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/5.1.jpg)

![Меню](https://github.com/DanilBorovyagin/software_engine/blob/Тема_10/tema_10/5.2.jpg)

## Вывод

В данном коде мы создали кастомное исключение, и продемонстрировали его работаспособность на очень простеньком варианте кода. Решил сильно не замарачиваться, но суть понятна можно сделать исключения которые буду писать ошибки пользователю вслучае не коретного ввода, так же можно было зациклить ввод типо что бы после ошибки мы могли ещё раз вводить даные и так пока не введём коректные.

## общий Вывод по теме

Использование декораторов позволяет упростить код за счет вынесения повторяющейся функциональности в отдельные декораторы. Это делает код более читабельным и удобным для `support`.

Обработка исключений с помощью конструкций `try/except` повышает надежность и стабильность работы программы. Перехват исключений позволяет избежать аварийного завершения программы и вывести пользователю понятное сообщение об ошибке.

Создание собственных исключений дает возможность информировать пользователя о специфических ошибках, возникающих в нашей программе. Это облегчает отладку и `support` кода.

В целом, в рамках этой темы были рассмотрены важные инструменты `Python`, позволяющие писать качественный и надежный код. Полученные навыки можно эффективно применять в реальных проектах.